apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-premium # already create in az
  accessModes:
  - ReadWriteOnce
